services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./storage:/app/storage

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./.env
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules

  dashboard:
    build:
      context: ./admin-dashboard
    env_file:
      - ./.env
    ports:
      - "8501:8501"
    command: streamlit run streamlit_app.py --server.address 0.0.0.0 --server.port 8501
    volumes:
      - ./admin-dashboard:/app
